Onboarding instructions for adding AWS account
pulibrary/rdss-handbook pull request #52
Opened 2022-06-08 19:53 UTC by bess

Connected to https://github.com/pulibrary/pdc_discovery/issues/303

2022-06-09 11:33 UTC, carolyncole requested changes
@bess I went through the instructions and commented on my questions. Things were a bit vague.  I guessed best I could...  I'm going to guess on a region and see if that gets me past the error.

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +2. From the "Services" menu, select "IAM". Create a new user, with AWS credential type "Access Key". Add the new account to the group `rdss`.
I had to search for IAM in the search bar.  It was not part of my services.

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +2. From the "Services" menu, select "IAM". Create a new user, with AWS credential type "Access Key". Add the new account to the group `rdss`.
I then had to click users on the left.

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +2. From the "Services" menu, select "IAM". Create a new user, with AWS credential type "Access Key". Add the new account to the group `rdss`.
I there a user name I should specify? I guessed and put it in as my netid

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +2. Configure it using the Access key ID and Secret Access key attached to your account
Should link to: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-quickstart.html

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +2. Configure it using the Access key ID and Secret Access key attached to your account
Is there a default region we should pick?

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +2. Configure it using the Access key ID and Secret Access key attached to your account
Could also just put in the step `aws configure`

2022-06-09 11:33 UTC, carolyncole commented on onboarding.md
> +aws ec2 describe-instances --query 'Reservations[*].Instances[?not_null(PublicIpAddress)]' | jq -r '.[][]|.PublicIpAddress+" "+(.Tags[]|select(.Key=="Name").Value)'
I get this error 
`You must specify a region. You can also configure your region by running "aws configure".`

2022-06-09 11:35 UTC, carolyncole commented
After reading the aws documentation I chose a region of `us-east-1` and a type of `json` and the test command did give me some IP addresses

2022-06-09 17:29 UTC, jrgriffiniii approved these changes

2022-06-09 17:46 UTC, jrgriffiniii commented
Thank you very much for this, running the Playbook (as specified in https://github.com/pulibrary/princeton_ansible/pull/3080/files) confirmed that this was indeed adding me to the `rdss` group.

2022-06-10 13:44 UTC, jrgriffiniii approved these changes

2022-06-10 13:44 UTC, carolyncole approved these changes

2022-06-10 13:45 UTC, jrgriffiniii commented on onboarding.md
> +  * Use default region `us-east-1`
👍

2022-06-10 13:45 UTC, jrgriffiniii approved these changes

2022-06-10 13:45 UTC, merged